org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=moremnaspellicons
mod_name=Mana and Artifice - Custom Spell Icon Loader
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.vincenthuto.moremnaspellicons
mod_authors=VincentHuto

mod_description=Just a small addon for Mana and Artifice to allow players to load custom spell icons. 
